--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HULAHULA"."EMPLOYEE" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "HULAHULA"."EMPLOYEE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HULAHULA"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HULAHULA"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
