--------------------------------------------------------
--  File created - Tuesday-December-15-2015   
--------------------------------------------------------
@C:\Users\Nonnadda\Desktop\hulahula\DROP.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKTIME_SEQ.sql
@C:\Users\Nonnadda\Desktop\hulahula\CUSTOMER.sql
@C:\Users\Nonnadda\Desktop\hulahula\DEPARTMENT.sql
@C:\Users\Nonnadda\Desktop\hulahula\EMPLOYEE.sql
@C:\Users\Nonnadda\Desktop\hulahula\LOGIN.sql
@C:\Users\Nonnadda\Desktop\hulahula\RESERVATION.sql
@C:\Users\Nonnadda\Desktop\hulahula\REVIEW.sql
@C:\Users\Nonnadda\Desktop\hulahula\ROOM.sql
@C:\Users\Nonnadda\Desktop\hulahula\TOOL.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKS_ON.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKTIME.sql
--@C:\Users\Nonnadda\Desktop\hulahula\CUSTOMER_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\DEPARTMENT_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\EMPLOYEE_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\LOGIN_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\RESERVATION_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\REVIEW_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\ROOM_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\TOOL_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\WORKS_ON_DATA_TABLE.csv
--@C:\Users\Nonnadda\Desktop\hulahula\WORKTIME_DATA_TABLE.csv
@C:\Users\Nonnadda\Desktop\hulahula\CUSTOMER_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\DEPARTMENT_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\EMPLOYEE_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\LOGIN_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\RESERVATION_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\REVIEW_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\ROOM_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\TOOL_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKS_ON_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKTIME_PK.sql
@C:\Users\Nonnadda\Desktop\hulahula\CUSTOMER_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\DEPARTMENT_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\EMPLOYEE_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\LOGIN_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\RESERVATION_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\REVIEW_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\ROOM_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\TOOL_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKS_ON_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKTIME_CONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\EMPLOYEE_REFCONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\LOGIN_REFCONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\REVIEW_REFCONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\WORKS_ON_REFCONSTRAINT.sql
@C:\Users\Nonnadda\Desktop\hulahula\BI_WORKTIME.sql
@C:\Users\Nonnadda\Desktop\hulahula\DUAL.sql
