--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "HULAHULA"."RESERVATION" 
   (	"BOOKINGNUMBER" NUMBER, 
	"CHECKIN" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CUSTOMEREMAIL" VARCHAR2(50 BYTE), 
	"CHECKOUT" VARCHAR2(20 BYTE), 
	"GUESTS" NUMBER, 
	"RNUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
