--------------------------------------------------------
--  DDL for Table WORKTIME
--------------------------------------------------------

  CREATE TABLE "HULAHULA"."WORKTIME" 
   (	"ID" NUMBER, 
	"EVENT" VARCHAR2(50 BYTE), 
	"STARTDATE" VARCHAR2(50 BYTE), 
	"STARTTIME" VARCHAR2(50 BYTE), 
	"ENDDATE" VARCHAR2(50 BYTE), 
	"ENDTIME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
